### ISSUE TITLE
Settings in Settings crach

### ISSUE THREAD

**Issue by FP19662604** [bubbledevteam/diabox#11]
Try to open settings in Settings then the app closes.

java.lang.IndexOutOfBoundsException: Index: 14, Size: 9
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:397)
	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:453)
	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:419)
	at android.widget.Spinner.makeView(Spinner.java:726)
	at android.widget.Spinner.layout(Spinner.java:674)
	at android.widget.Spinner.onLayout(Spinner.java:636)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.widget.ScrollView.onLayout(ScrollView.java:1662)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:811)
	at android.view.View.layout(View.java:22169)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3173)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2683)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by PieterDeBruijn** [comment]
2021.03.04
@bubbledevteam bubbledevteam released this 13 minutes ago
...
2--Fix App crash when click setting on the devices;
Try the latest release! Let me know if this fixes things for you, so this ticket can be closed.

**Comment by PieterDeBruijn** [comment]
Did you delete al stored data & cache before updating? Or did you uninstall the old one?

**Comment by FP19662604** [comment]
I just installed the app 2021-03-04 over the old 2021-02-??.

Then I wanted to look at the settings and the app crached.


Op do 4 mrt. 2021 16:14 schreef Pieter de Bruijn <notifications@github.com>:

**Comment by PieterDeBruijn** [comment]
> I just installed the app 2021-03-04 over the old 2021-02-??. Then I wanted to look at the settings and the app crached.
Sure, would have tried that myself too. Maybe you can check the Android settings from the Diabox App (App info) and delete storage and cache and try opening the app again.

**Comment by FP19662604** [comment]
Ok, I'll check it out.  No problems anymore. Accept still no calibrations
with FSL2.

Op do 4 mrt. 2021 16:47 schreef Pieter de Bruijn <notifications@github.com>:

**Comment by PieterDeBruijn** [comment]
To be clear: the crash has been resolved by a clean start of the latest version?

Calibrations arent a feature of FreeStyle Libre 2, as far as I know. Dexcom 6 does accept manual calibrations. Or did you mean something else?

**Comment by FP19662604** [comment]
Correct.

I have a different number between real blood value and the FSL2 value. Is
it not possible to give a correction for the number?

Greetings Frank

Op za 6 mrt. 2021 21:31 schreef Pieter de Bruijn <notifications@github.com>:

**Comment by PieterDeBruijn** [comment]
No Abbott does not have this option. You should try the Dexcom (currently still the G6) if you want this.

**Comment by FP19662604** [comment]
Sorry to say but if xdrip+ can do this with FSL1 why can't you do it with
FSL2?

Op zo 7 mrt. 2021 17:00 schreef Pieter de Bruijn <notifications@github.com>:

**Comment by FP19662604** [comment]
Dexcom 6 is not founded for me in my country and FSL2 is. I don't have 4000
euro to found it my self per year.

Op zo 7 mrt. 2021 18:19 schreef Frank van Olffen <frankvanolffen@gmail.com>:

**Comment by PieterDeBruijn** [comment]
https://github.com/bubbledevteam/diabox/releases/tag/2021.03.08
new release says it adds Calibration. Try it!

**Comment by FP19662604** [comment]
Thanks, I'll check it out.

Op ma 8 mrt. 2021 10:27 schreef Pieter de Bruijn <notifications@github.com>:

**Comment by PieterDeBruijn** [comment]
Could you mark this bug closed? If there is any issue with Calibration, you can always open a ticket under that name as a separate issue.

**Comment by FP19662604** [comment]
Will do.

Op ma 8 mrt. 2021 11:12 schreef Pieter de Bruijn <notifications@github.com>:
