### ISSUE TITLE
BUG: Wear OS watchface crashing on start

### ISSUE THREAD

**Issue by tim162** [bubbledevteam/diabox#3]
Wear OS watchface is crashing every time I want to choose it. I was able to fetch the log data:

01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: FATAL EXCEPTION: main
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: Process: com.outshineiot.diabox, PID: 11432
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.measure(int, int)' on a null object reference
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at com.outshineiot.diabox.BaseWatchFace$1.onLayoutInflated(BaseWatchFace.java:146)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.support.wearable.view.WatchViewStub.inflate(WatchViewStub.java:180)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.support.wearable.view.WatchViewStub.onApplyWindowInsets(WatchViewStub.java:147)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at com.outshineiot.diabox.BaseWatchFace.onLayout(BaseWatchFace.java:121)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at com.ustwo.clockwise.WatchFace$WatchFaceEngine.onApplyWindowInsets(WatchFace.java:395)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.service.wallpaper.WallpaperService$Engine.updateSurface(WallpaperService.java:1004)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.service.wallpaper.WallpaperService$Engine.attach(WallpaperService.java:1086)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1409)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:220)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6752)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-29 22:54:35.731 10058 11432 11432 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by PieterDeBruijn** [comment]
Hi Tim, there is a new version, could you try if this fixes/changes things?
https://github.com/bubbledevteam/diabox/releases/tag/2021.03.04

**Comment by tim162** [comment]
@PieterDeBruijn Sorry but I can't test it anymore - I had to switch back to xDrip as there were still too many bugs in Diabox

**Comment by polcarmona** [comment]
> Hi Tim, there is a new version, could you try if this fixes/changes things?
> https://github.com/bubbledevteam/diabox/releases/tag/2021.03.04

I have tried 2021.03.10 version with Sony Smartwatch 3 Wear OS 1.5 and the watchface is crashing.  Although the application can be started within the watch but it does not receive data. 

Would it be possible to use the watch in standalone mode without a mobile? 

Thank you very much for the work done!

**Comment by PieterDeBruijn** [comment]
Could you try the latest version?

Wear OS is Android right? You could try to let it connect directly via Bluetooth. I'm pretty sure that could work.

**Comment by Eddy69** [comment]
In case it's related: I can't install DiaBox on my Ticwatch Pro 3 (WearOS). It just doesn't appear in the "apps on phone" category. 
It once did, but I removed it because it didn't gave any values. Rebooted phone and watch several times.

**Comment by polcarmona** [comment]
> Could you try the latest version?
> 
> Wear OS is Android right? You could try to let it connect directly via Bluetooth. I'm pretty sure that could work.

Yes! It's Android. The lastest version is working on my watch, but the watch face not
